name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cuisinecraft   # Google Cloud project ID from GitHub Secrets
  GKE_CLUSTER: cuisinecraft-cluster       # GKE cluster name
  GKE_ZONE: europe-west4-a                # GKE cluster zone
  IMAGE_NAME: cuisine-craft-ingredient-service # Docker image name

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Google Cloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}  # Service account key from GitHub Secrets
          project_id: ${{ env.PROJECT_ID }}

      # Step 3: Authenticate Docker with gcloud
      - name: Configure Docker Authentication
        run: gcloud --quiet auth configure-docker

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .

      # Step 5: Push Docker Image to GCR
      - name: Push Docker Image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
