name: Test, Build, and Push to Container Registry (Gradle)

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Specify the Java version you use
          distribution: temurin  # Options: 'temurin', 'zulu', etc.

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 5: Build and Test with Gradle
      - name: Build and Test with Gradle
        run: ./gradlew clean build

      # Step 6: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cuisinecraft  # Replace with your Google Cloud project ID
          service_account_key: ${{ secrets.GCLOUD_KEY }}

      # Step 7: Configure Docker for Container Registry
      - name: Configure Docker for Container Registry
        run: gcloud auth configure-docker

      # Step 8: Build the Docker image
      - name: Build Docker Image
        run: docker build -t gcr.io/cuisinecraft/cuisine-craft-ingredient-service:latest .

      # Step 9: Push the Docker image to Container Registry
      - name: Push Docker Image
        run: docker push gcr.io/cuisinecraft/cuisine-craft-ingredient-service:latest
